language: python

sudo: false

node_js:
  - 12

env:
  global:
    - ENV_BUCKET_NAME=coronanrw
    - AWS_REGION=eu-central-1

cache: yarn

before_script:
  - yarn

skript: echo "no tests 😟"

deploy:
  - provider: script
    skip_cleanup: true
    script: yarn serverless deploy
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: yarn serverless deploy
    on:
      branch: production
