service: corona-scraper-nrw

provider:
  name: aws
  region: eu-central-1
  runtime: python3.8
  stage: ${env:STAGE}
  environment:
    BUCKET_NAME: "coronanrw-${self:provider.stage}"
    SENTRY_URI: ${env:SENTRY_URI}
    SLACK_WEBHOOK: ${env:SLACK_WEBHOOK, ''}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::coronanrw-${self:provider.stage}/*"

functions:
  scrape:
    handler: handler.scrape
    timeout: 120
    events:
      - schedule:
          name: ${self:service}-${self:provider.stage}-scrape
          rate: rate(3 minutes)
          enabled: true
  error:
    handler: handler.error
  notify:
    handler: handler.notify

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    slim: true

package:
  exclude:
    - node_modules/**
    - venv/**
