service: corona-scraper-nrw

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    slim: true

package:
  exclude:
    - node_modules/**
    - venv/**
