service: corona-scraper-nrw

provider:
  name: aws
  runtime: python3.8
  stage: staging

functions:
  scrape:
    handler: handler.scrape
    timeout: 120
    events:
      - schedule:
          name: ${self:service}-${self:provider.stage}-scrape
          rate: rate(3 minutes)
          enabled: true


plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    slim: true

package:
  exclude:
    - node_modules/**
    - venv/**
